# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6096070dde04bab9b06eef7331d1cd9e48fa70759656fe491850f6192b8a448ef746903454495e73a541e60bef8908026ff63358b3d2aac4cec07b5a5e2d52f2

test:
  secret_key_base: 52dc401583d1b2555beff91457aa0eb532bec93bd303a8f5fde26a31a91e1df17da7540daa095f49faa921a81c2dabbee1d4593768447d86616862e167ec9fa5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
